### ISSUE TITLE
Convert master to build FOS 1.X, not 2.X

### ISSUE THREAD

**Issue by FinancedHydra** [FOGProject/fos#4]
Putting FOS 1.X into this repository will allow us to automate the building and publishing of FOS 1.X, in addition to making contributions simpler.

**Comment by Sebastian-Roth** [comment]
Alright, here is a first big shot to bring all the FOS relevant stuff over to this repo: https://github.com/FOGProject/fos/commit/1ffca088031720c67471e9422d7dc9c4734e8ed7

Still needs some work to make the building as seamless as possible.

**Comment by Sebastian-Roth** [comment]
* Kernel build is working and configs are updated to 4.13.4 as we have in fogproject working branch ([d98e7f](https://github.com/FOGProject/fos/commit/d98e7f984971ff036f4c078b3009ab7f40f69f42))
* By default build.sh now builds both architectures ([1ae6fa](https://github.com/FOGProject/fos/commit/1ae6fabcfd54c671ad1749affe997683d7d22049))

**Comment by mastacontrola** [comment]
I’ll try working on getting buildroot updated and remove our zstd scripts once I know all is working properly.

**Comment by mastacontrola** [comment]
Building FS appears to be working. It will successfully construct 64 bit inits, 64 bit kernels, and 32 bit kernels. It fails to build 32 bit inits, though this was a part of the make command line not containing the ARCH flag. I've modified the build script to do this appropriately.

Some simple  notes:
1. Buildroot v2017.11.2
2. GCC is using version 7.x
3. Kernel header is using 4.13.6
4. glibc is using 2.29.1
5. Removed usbreset from fog.mk and the package/fog/src/ directory.
6. Removed the fog.mk scripts loop as we handle this via overlay now.
7. Updated gptfdisk to 1.0.1 while still enabling fixparts binary.
8. Removed the directory creation of /usr/share/clamav
9. Removed zstd from newConf.in
10. Using ext4 instead of ext2 for filesystem.

Kernel Building will make 4.15.2, may think about making this a switch argument, same for buildroot, though doing buildroot takes a lot more effort as each iteration we have check for legacy deprecations or the build will fail.

build.sh has been updated.

Dockerfile has been updated to include libelf-dev and libelf-dev:i386. Currently using mastacontrola/fos-builder for my testing as I don't have collaborator/rights to fogproject/fos-builder yet.

travis.yml has been updated to add libelf-dev to its layout.

**Comment by mastacontrola** [comment]
README.md has been added with information on what is needed and how to do it.
FOGProject/fos-builder has been updated with similar information on docker hub as well.

I think it's okay to close this now, of course if there's anything else that needs to be added either a new issue/or reopening this one is simple enough.
